### ISSUE TITLE
Горизонтальный скролл

### ISSUE THREAD

**Issue by sbmaxx** [phpprog/tt#1]
https://yadi.sk/i/O-j2_VvWeEttX

Контент весь помещается

**Comment by pskucherov** [comment]
fixed (если об этом скролле речь была)

**Comment by sbmaxx** [comment]
Не, не оно.

Вот это https://github.com/phpprog/tt/blob/master/desktop.blocks/text/text.css#L4 раздвигает всю страницу. Некорректный CSS. Issue о пользе линтеров :)
