### ISSUE TITLE
Изображения с браузерами названы не по БЭМу

### ISSUE THREAD

**Issue by sbmaxx** [phpprog/tt#3]
Ну и что-то странное с путями. Проще, наверное, уже в CSS это всё загнать?

``` js
[ { color: '#0f0', 'text: 'Ch' } ].map(functionion(o) { return { tag: 'span', attrs: { style: 'color: '.. } } }).join('');
```

``` js
        for (i = 0; i < elems.length; i++) {
```

Тут тоже что-нибудь из ES5

**Comment by pskucherov** [comment]
там путь должен быть в src записан, в css загонять точно не надо. Остальное поправил.
