### ISSUE TITLE
progress-bar

### ISSUE THREAD

**Issue by sbmaxx** [phpprog/tt#8]
Есть ощущение, что можно сверстать меньшим количеством вложенных элементов.
- у самого блока очень большие отступы, что немного не про "АНБ". Лучше отступы делать у внешних блоков, чтобы прогресс бар можно было брать и вставлять в другое место, чтобы он вёрстку не распирал

**Comment by pskucherov** [comment]
убрал элемент text, меньше вроде нельзя. 

Отступы только для демки, чтобы блоки друг на друга не налезали. А так-то да, по-честному их надо вообще убрать. 

Что за АНБ? )

**Comment by sbmaxx** [comment]
Абсолютно Независимые Блоки

**Comment by pskucherov** [comment]
ааа, точно-точно ... а мне чёт только Сноуден на ум пришёл )))
