### ISSUE TITLE
browsers

### ISSUE THREAD

**Issue by sbmaxx** [phpprog/tt#9]
Не очень понимаю семантику второго блока browsers, который сразу содержит в себе текст про " thumb_error". Кажется, это подписи к браузерам и тумбнейлы лучше делать единым блокам, не разрывая связь между элементами. А получается что визуальная связь присутствует, а с точки зрения кода — нет

**Comment by pskucherov** [comment]
это две демки использования одного и того же блока. 
Первый - тумбы браузеров. Второй - он же, но когда нет инета / отключены картинки. 

Визуальной связи там быть не должно, т.к. может быть показан только один из вариантов.
